Vagrant.configure("2") do |config| 
    config.vm.box = "spox/ubuntu-arm" 
    config.vm.box_version = "1.0.0"
    config.vm.network "private_network", ip: "192.168.56.11"
    config.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = true
      vmware.allowlist_verified = true
     end
     # Provisioning configuration for Ansible. 
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.host_key_checking = false
        ansible.compatibility_mode = "2.0"
        ansible.config_file = "./ansible.cfg"
    end
end