version: '3'


services:
  container1:
    build: 
        context: /tmp/vm-4.wrk0mQNr
        dockerfile: ./Dockerfile
        args:
            USER: lois
    ports:
      - "2201:22"
    networks:
      - ansible-net

  container2:
    build: 
        context: /tmp/vm-4.wrk0mQNr
        dockerfile: ./Dockerfile
        args:
            USER: lois
    ports:
      - "2202:22"
    networks:
      - ansible-net

  container3:
    build: 
        context: /tmp/vm-4.wrk0mQNr
        dockerfile: ./Dockerfile
        args:
            USER: lois
    ports:
      - "2203:22"
    networks:
      - ansible-net

networks:
  ansible-net:
